# Generated by Django 5.2.1 on 2025-05-17 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Permisos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permiso',
            name='privilegios',
            field=models.ManyToManyField(related_name='permisos', to='Permisos.privilegio'),
        ),
        migrations.AddField(
            model_name='rol',
            name='usuarios',
            field=models.ManyToManyField(related_name='roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privilegio',
            name='roles',
            field=models.ManyToManyField(related_name='privilegios', to='Permisos.rol'),
        ),
    ]
