# Generated by Django 5.2.1 on 2025-05-26 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_add_curso_to_usuario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
