# Generated by Django 5.2.1 on 2025-06-12 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.DecimalField(decimal_places=6, help_text='Precisión del modelo (R² score)', max_digits=10)),
                ('error_promedio', models.DecimalField(decimal_places=6, help_text='Error promedio absoluto (MAE)', max_digits=10)),
                ('metricas_detalladas', models.JSONField(default=dict, help_text='Métricas detalladas del entrenamiento')),
                ('fecha_entrenamiento', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_entrenamiento', to='machine_learning.datasetacademico')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_entrenamiento', to='machine_learning.modeloml')),
            ],
            options={
                'verbose_name': 'Resultado de Entrenamiento',
                'verbose_name_plural': 'Resultados de Entrenamiento',
                'db_table': 'ml_resultado_entrenamiento',
                'ordering': ['-fecha_entrenamiento'],
            },
        ),
    ]
