# Generated by Django 5.2.1 on 2025-05-17 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cursos', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletin',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletines', to='Usuarios.estudiante'),
        ),
        migrations.AddField(
            model_name='materia',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='Cursos.curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='Cursos.nivel'),
        ),
        migrations.AddField(
            model_name='notas',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='Usuarios.estudiante'),
        ),
        migrations.AddField(
            model_name='notas',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='Cursos.materia'),
        ),
        migrations.AddField(
            model_name='boletin',
            name='notas',
            field=models.ManyToManyField(related_name='boletines', to='Cursos.notas'),
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('nombre', 'curso')},
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nivel', 'grado', 'paralelo')},
        ),
    ]
