# Generated by Django 5.2.1 on 2025-05-26 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0005_asistencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='observacion',
            new_name='ausente',
        ),
    ]
