# Generated by Django 5.2.1 on 2025-05-26 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0006_rename_observacion_to_ausente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='ausente',
        ),
    ]
