# Generated by Django 5.2.1 on 2025-05-26 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0007_rename_observacion_to_ausente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletin',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol__nombre': 'Estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='boletines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notas',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol__nombre': 'Estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to=settings.AUTH_USER_MODEL),
        ),
    ]
