# Generated by Django 5.2.1 on 2025-05-29 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0008_add_curso_to_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('EXAMEN', 'Examen'), ('PARTICIPACION', 'Participación en Clase'), ('EXPOSICION', 'Exposición Grupal'), ('TRABAJO', 'Trabajo Práctico')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porcentaje_minimo', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje mínimo que debe representar en la nota final', max_digits=5)),
                ('porcentaje_maximo', models.DecimalField(decimal_places=2, default=100.0, help_text='Porcentaje máximo que puede representar en la nota final', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Evaluación',
                'verbose_name_plural': 'Tipos de Evaluación',
                'db_table': 'tipos_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_asignacion', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('fecha_limite', models.DateField(blank=True, help_text='Fecha límite para entrega tardía', null=True)),
                ('nota_maxima', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('nota_minima_aprobacion', models.DecimalField(decimal_places=2, default=51.0, max_digits=5)),
                ('porcentaje_nota_final', models.DecimalField(decimal_places=2, help_text='Porcentaje que representa en la nota final de la materia', max_digits=5)),
                ('permite_entrega_tardia', models.BooleanField(default=False)),
                ('penalizacion_tardio', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de penalización por entrega tardía', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('publicado', models.BooleanField(default=False, help_text='Si está visible para los estudiantes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='Cursos.materia')),
                ('tipo_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.tipoevaluacion')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'evaluaciones',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_sobre', models.DecimalField(decimal_places=2, help_text='Nota máxima posible', max_digits=5)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('entrega_tardia', models.BooleanField(default=False)),
                ('penalizacion_aplicada', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('retroalimentacion', models.TextField(blank=True, null=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('fecha_calificacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='Cursos.evaluacion')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'calificaciones',
                'unique_together': {('evaluacion', 'estudiante')},
            },
        ),
    ]
