# Generated by Django 5.2.1 on 2025-05-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0009_remove_groups_and_update_evaluaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoevaluacion',
            name='porcentaje_maximo',
        ),
        migrations.RemoveField(
            model_name='tipoevaluacion',
            name='porcentaje_minimo',
        ),
        migrations.AlterField(
            model_name='tipoevaluacion',
            name='nombre',
            field=models.CharField(choices=[('EXAMEN', 'Examen'), ('PARTICIPACION', 'Participación en Clase'), ('TRABAJO', 'Trabajo Práctico')], max_length=50, unique=True),
        ),
    ]
