# Generated by Django 5.2.1 on 2025-05-31 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0010_remove_percentage_fields'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(choices=[(1, 'Primer Trimestre'), (2, 'Segundo Trimestre'), (3, 'Tercer Trimestre')])),
                ('nombre', models.CharField(help_text='Ej: Primer Trimestre 2025', max_length=50)),
                ('año_academico', models.IntegerField(help_text='Año académico al que pertenece')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_limite_evaluaciones', models.DateField(help_text='Fecha límite para registrar evaluaciones')),
                ('fecha_limite_calificaciones', models.DateField(help_text='Fecha límite para registrar calificaciones')),
                ('nota_minima_aprobacion', models.DecimalField(decimal_places=2, default=51.0, max_digits=5)),
                ('porcentaje_asistencia_minima', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('CERRADO', 'Cerrado')], default='PLANIFICADO', max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trimestres_creados', to='Usuarios.Usuario')),
            ],
            options={
                'verbose_name': 'Trimestre',
                'verbose_name_plural': 'Trimestres',
                'db_table': 'trimestres',
                'ordering': ['año_academico', 'numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='trimestre',
            constraint=models.UniqueConstraint(fields=['numero', 'año_academico'], name='unique_trimestre_año'),
        ),
    ]