# Generated by Django 5.2.1 on 2025-05-31 15:10

from django.db import migrations
from datetime import date

def create_default_trimestres(apps, schema_editor):
    """Crear trimestres por defecto para el año actual"""
    Trimestre = apps.get_model('Cursos', 'Trimestre')
    
    año_actual = date.today().year
    
    # Crear los tres trimestres para el año actual
    trimestres = [
        {
            'numero': 1,
            'nombre': f'Primer Trimestre {año_actual}',
            'año_academico': año_actual,
            'fecha_inicio': date(año_actual, 2, 1),
            'fecha_fin': date(año_actual, 5, 31),
            'fecha_limite_evaluaciones': date(año_actual, 5, 25),
            'fecha_limite_calificaciones': date(año_actual, 6, 5),
            'estado': 'ACTIVO'
        },
        {
            'numero': 2,
            'nombre': f'Segundo Trimestre {año_actual}',
            'año_academico': año_actual,
            'fecha_inicio': date(año_actual, 6, 1),
            'fecha_fin': date(año_actual, 9, 30),
            'fecha_limite_evaluaciones': date(año_actual, 9, 25),
            'fecha_limite_calificaciones': date(año_actual, 10, 5),
            'estado': 'PLANIFICADO'
        },
        {
            'numero': 3,
            'nombre': f'Tercer Trimestre {año_actual}',
            'año_academico': año_actual,
            'fecha_inicio': date(año_actual, 10, 1),
            'fecha_fin': date(año_actual, 12, 20),
            'fecha_limite_evaluaciones': date(año_actual, 12, 15),
            'fecha_limite_calificaciones': date(año_actual, 12, 25),
            'estado': 'PLANIFICADO'
        }
    ]
    
    for data in trimestres:
        Trimestre.objects.create(**data)

def reverse_default_trimestres(apps, schema_editor):
    """Eliminar trimestres creados"""
    Trimestre = apps.get_model('Cursos', 'Trimestre')
    año_actual = date.today().year
    Trimestre.objects.filter(año_academico=año_actual).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('Cursos', '0011_create_trimestre_table'),
    ]

    operations = [
        migrations.RunPython(create_default_trimestres, reverse_default_trimestres),
    ]