# Generated by Django 5.2.1 on 2025-05-31 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0012_create_default_trimestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='trimestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='Cursos.trimestre'),
            preserve_default=False,
        ),
    ]