# Generated by Django 5.2.1 on 2025-05-31 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0013_add_trimestre_to_evaluacion'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromedioTrimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_evaluaciones', models.DecimalField(decimal_places=2, help_text='Promedio de evaluaciones del trimestre', max_digits=5)),
                ('promedio_final', models.DecimalField(decimal_places=2, help_text='Promedio final considerando todos los factores', max_digits=5)),
                ('total_clases', models.IntegerField(default=0)),
                ('asistencias', models.IntegerField(default=0)),
                ('porcentaje_asistencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('aprobado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('calculado_automaticamente', models.BooleanField(default=True)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promedios_trimestrales', to='Usuarios.Usuario')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promedios_trimestrales', to='Cursos.materia')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promedios', to='Cursos.trimestre')),
            ],
            options={
                'verbose_name': 'Promedio Trimestral',
                'verbose_name_plural': 'Promedios Trimestrales',
                'db_table': 'promedios_trimestrales',
                'ordering': ['-trimestre__año_academico', '-trimestre__numero', 'materia__nombre'],
            },
        ),
        migrations.CreateModel(
            name='PromedioAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_academico', models.IntegerField()),
                ('promedio_trimestre_1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('promedio_trimestre_2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('promedio_trimestre_3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('promedio_anual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('aprobado_anual', models.BooleanField(default=False)),
                ('porcentaje_asistencia_anual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('calculado_automaticamente', models.BooleanField(default=True)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promedios_anuales', to='Usuarios.Usuario')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promedios_anuales', to='Cursos.materia')),
            ],
            options={
                'verbose_name': 'Promedio Anual',
                'verbose_name_plural': 'Promedios Anuales',
                'db_table': 'promedios_anuales',
                'ordering': ['-año_academico', 'materia__nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='promediotrimestral',
            constraint=models.UniqueConstraint(fields=['estudiante', 'materia', 'trimestre'], name='unique_promedio_trimestral'),
        ),
        migrations.AddConstraint(
            model_name='promedioanual',
            constraint=models.UniqueConstraint(fields=['estudiante', 'materia', 'año_academico'], name='unique_promedio_anual'),
        ),
    ]