# Generated by Django 5.2.1 on 2025-06-06 22:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0015_add_content_type_to_calificacion'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('content_type', 'object_id', 'estudiante')},
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='nota_sobre',
        ),
    ]
