# Generated by Django 5.2.1 on 2025-06-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0016_add_unique_constraint_to_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacionparticipacion',
            name='criterios_participacion',
        ),
        migrations.RemoveField(
            model_name='evaluacionparticipacion',
            name='escala_calificacion',
        ),
    ]
