# Generated by Django 5.2.1 on 2025-06-12 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0017_remove_evaluacionparticipacion_criterios_participacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='trimestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='Cursos.trimestre'),
            preserve_default=False,
        ),
    ]
